"""empty message

Revision ID: 3c09b4ac3d90
Revises: b85882026925
Create Date: 2021-02-26 01:42:45.852036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3c09b4ac3d90'
down_revision = 'b85882026925'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorites', 'tipo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('tipo', mysql.VARCHAR(length=250), nullable=False))
    # ### end Alembic commands ###
