"""empty message

Revision ID: 832d3cef560a
Revises: 9e6e37af99c1
Create Date: 2021-03-03 15:41:01.530285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '832d3cef560a'
down_revision = '9e6e37af99c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fav_name', table_name='favorites')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fav_name', 'favorites', ['fav_name'], unique=True)
    # ### end Alembic commands ###
