"""empty message

Revision ID: 83f2461ecd21
Revises: 3c09b4ac3d90
Create Date: 2021-02-26 01:51:53.762665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83f2461ecd21'
down_revision = '3c09b4ac3d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('fav_name', sa.String(length=250), nullable=False))
    op.create_unique_constraint(None, 'favorites', ['fav_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorites', type_='unique')
    op.drop_column('favorites', 'fav_name')
    # ### end Alembic commands ###
