"""empty message

Revision ID: b85882026925
Revises: cba47bd44eb0
Create Date: 2021-02-25 23:51:33.250871

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b85882026925'
down_revision = 'cba47bd44eb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('tipo', sa.String(length=250), nullable=False))
    op.drop_constraint('favorites_ibfk_3', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_1', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_4', 'favorites', type_='foreignkey')
    op.drop_constraint('favorites_ibfk_2', 'favorites', type_='foreignkey')
    op.drop_column('favorites', 'planet_id')
    op.drop_column('favorites', 'planet_name')
    op.drop_column('favorites', 'people_id')
    op.drop_column('favorites', 'people_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('people_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('favorites', sa.Column('people_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorites', sa.Column('planet_name', mysql.VARCHAR(length=250), nullable=True))
    op.add_column('favorites', sa.Column('planet_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('favorites_ibfk_2', 'favorites', 'people', ['people_name'], ['name'])
    op.create_foreign_key('favorites_ibfk_4', 'favorites', 'planets', ['planet_name'], ['name'])
    op.create_foreign_key('favorites_ibfk_1', 'favorites', 'people', ['people_id'], ['id'])
    op.create_foreign_key('favorites_ibfk_3', 'favorites', 'planets', ['planet_id'], ['id'])
    op.drop_column('favorites', 'tipo')
    # ### end Alembic commands ###
